version: '3.3'
services:
  markdown-notes:
    build: ../
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    container_name: markdown-notes
    ports:
      - '3000:3000'
    volumes:
      - ../:/workspace:cached
      - /workspace/node_modules/ # for disk performance
      # for prezto
      - ~/.zshrc:/root/.zshrc
      - ~/.zlogin:/root/.zlogin
      - ~/.zprofile:/root/.zprofile
      - ~/.zenv:/root/.zenv
      - ~/.zpreztorc:/root/.zpreztorc
      - ~/.zprezto:/root/.zprezto
